# Generated by Django 5.1.3 on 2024-12-01 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetSetGoApp', '0002_alter_report_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Collegename', models.CharField(blank=True, max_length=30, null=True)),
                ('Address', models.CharField(blank=True, max_length=30, null=True)),
                ('Phone', models.IntegerField(blank=True, null=True)),
                ('Email', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstructionsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Instruction', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Notification', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Schoolname', models.CharField(blank=True, max_length=30, null=True)),
                ('Address', models.CharField(blank=True, max_length=30, null=True)),
                ('Phone', models.IntegerField(blank=True, null=True)),
                ('Email', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamsheetTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(blank=True, max_length=30, null=True)),
                ('teammembers', models.IntegerField(blank=True, null=True)),
                ('discription', models.CharField(blank=True, max_length=100, null=True)),
                ('rules', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('gender', models.CharField(blank=True, max_length=30, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('Address', models.CharField(blank=True, max_length=30, null=True)),
                ('Phone', models.IntegerField(blank=True, null=True)),
                ('Email', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='EventOrgainser',
            new_name='EventOrgainserTable',
        ),
        migrations.RenameModel(
            old_name='Event',
            new_name='EventTable',
        ),
        migrations.RenameModel(
            old_name='Report',
            new_name='ReportTable',
        ),
        migrations.RenameModel(
            old_name='Services',
            new_name='ServicesTable',
        ),
        migrations.CreateModel(
            name='SponsorsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsors', models.CharField(blank=True, max_length=30, null=True)),
                ('Event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GetSetGoApp.clubtable')),
            ],
        ),
        migrations.CreateModel(
            name='MembersTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TEAMSHEET', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GetSetGoApp.teamsheettable')),
                ('USER', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GetSetGoApp.usertable')),
            ],
        ),
    ]
